vim.o.number = true
vim.o.rnu = true
vim.o.numberwidth = 1
vim.o.clipboard = "unnamed" 
vim.o.swapfile = false
vim.o.backup = false
vim.o.t_Co = "256k" 
vim.o.background = "dark"
vim.o.showmatch = true
vim.o.showmode = false
vim.o.sw = 2
vim.o.hlsearch = true
vim.o.linebreak = true
vim.o.incsearch = true
vim.o.termguicolors = true
vim.o.scrolloff = 10
vim.o.signcolumn = "yes"
vim.o.ignorecase = true
vim.o.updatetime = 300
vim.o.splitright = true
-- vim.o.undodir = "~/.config/nvim/undo"
-- vim.o.undofile = true
-- vim.o.undolevels = 50
